In [1]:
import pandas as pd

In [4]:
ds=pd.read_csv('loan.csv')

In [5]:
ds

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [6]:
ds.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [9]:
ds.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [11]:
ds["Gender"].mode()[0]

0    Male
Name: Gender, dtype: object

'Male'

In [13]:
ds['Gender'].fillna(ds["Gender"].mode()[0],inplace=True)

<ipython-input-13-8eb2fe533d69>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds['Gender'].fillna(ds["Gender"].mode()[0],inplace=True)

In [14]:
ds.isnull().sum()

Loan_ID               0
Gender                0
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [18]:
ds["Gender"].unique()

array(['Male', 'Female'], dtype=object)

# **Dummies Method**

get_dummies

In [37]:
cds=ds.copy()

In [38]:
dummies=pd.get_dummies(cds["Gender"],prefix='Gender_')

In [39]:
dummies

     Gender__Female  Gender__Male
0             False          True
1             False          True
2             False          True
3             False          True
4             False          True
..              ...           ...
609            True         False
610           False          True
611           False          True
612           False          True
613            True         False

[614 rows x 2 columns]

In [40]:
dummies=dummies.astype(int)

In [41]:
dummies

     Gender__Female  Gender__Male
0                 0             1
1                 0             1
2                 0             1
3                 0             1
4                 0             1
..              ...           ...
609               1             0
610               0             1
611               0             1
612               0             1
613               1             0

[614 rows x 2 columns]

In [42]:
dp=pd.concat([cds,dummies],axis=1)     #axis=1 mean column wise

In [43]:
dp

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Gender__Female,Gender__Male
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,0,1
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,0,1
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,0,1
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,0,1
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,1,0
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,0,1
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,0,1
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,0,1
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,1,0

# **One Hot Encoder**

In [75]:
ds['Married'].fillna(ds['Married'].mode()[0],inplace=True)
ds.isnull().sum()

<ipython-input-75-9ff99bd79c50>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds['Married'].fillna(ds['Married'].mode()[0],inplace=True)

Loan_ID               0
Gender                0
Married               0
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [76]:
new_data=ds[['Gender','Married']]

In [77]:
new_data

     Gender Married
0      Male      No
1      Male     Yes
2      Male     Yes
3      Male     Yes
4      Male      No
..      ...     ...
609  Female      No
610    Male     Yes
611    Male     Yes
612    Male     Yes
613  Female      No

[614 rows x 2 columns]

In [78]:
from sklearn.preprocessing import OneHotEncoder

In [79]:
ohe=OneHotEncoder() #creating object of one hot encoder

In [86]:
ar=ohe.fit_transform(new_data).toarray()

In [87]:
ar

array([[0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       ...,
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [82]:
pd.get_dummies(new_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  614 non-null    bool
 1   Gender_Male    614 non-null    bool
 2   Married_No     614 non-null    bool
 3   Married_Yes    614 non-null    bool
dtypes: bool(4)
memory usage: 2.5 KB

In [88]:
after_label_ar=pd.DataFrame(ar,columns=["Gender_Female","Gender_Male","Married_NO","Married_Yes"])
after_label_ar

     Gender_Female  Gender_Male  Married_NO  Married_Yes
0              0.0          1.0         1.0          0.0
1              0.0          1.0         0.0          1.0
2              0.0          1.0         0.0          1.0
3              0.0          1.0         0.0          1.0
4              0.0          1.0         1.0          0.0
..             ...          ...         ...          ...
609            1.0          0.0         1.0          0.0
610            0.0          1.0         0.0          1.0
611            0.0          1.0         0.0          1.0
612            0.0          1.0         0.0          1.0
613            1.0          0.0         1.0          0.0

[614 rows x 4 columns]